source "https://rubygems.org"

group :development do
  gem "pry"
  gem "pry-byebug"
  gem "pry-stack_explorer"
  gem "pry-rescue"
end

gem "rake"
gem "rspec-retry"
gem "serverspec", "~> 2.37.0"
gem "dockerspec", "~> 0.3.0"
